#!/usr/bin/ansible-playbook
---
#example run:
# ansible-playbook -e "host=ops-node-compute-abcde" oo-sdn-restart.yml
#

- name: Check vars
  hosts: localhost
  gather_facts: false

  pre_tasks:
  - fail:
      msg: "Playbook requires host to be set"
    when: host is not defined or host == ''

- name: Restart openshift/docker (and monitoring containers)
  hosts: oo_version_3:&oo_name_{{ host }}
  gather_facts: false
  user: root

  tasks:
  - name: stop openshift/docker
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
    - atomic-openshift-node
    - docker

  - name: restart openvswitch
    service:
      name: openvswitch
      state: restarted

  - name: wait 5 sec
    pause:
      seconds: 5

  - name: start openshift/docker
    service:
      name: "{{ item }}"
      state: started
    with_items:
    - atomic-openshift-node
    - docker

  - name: start monitoring containers
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
    - oso-rhel7-host-monitoring
