# Generated by Django 2.2.10 on 2020-04-13 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField(allow_unicode=True, max_length=128, unique=True)),
                ('type', models.CharField(choices=[('python', 'python'), ('shell', 'shell')], default='shell', max_length=64)),
                ('interpreter', models.CharField(default='/usr/bin/bash', max_length=64)),
                ('content', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
