# Generated by Django 2.2.10 on 2020-04-14 10:11

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0075_auto_20200408_0803'),
        ('ops', '0002_remove_script_interpreter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry')], default='PENDING', max_length=16)),
                ('num', models.IntegerField(default=1)),
                ('result_summary', common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Result summary')),
                ('result_raw', common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Result raw')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time')),
                ('date_start', models.DateTimeField(null=True, verbose_name='Start time')),
                ('date_end', models.DateTimeField(null=True, verbose_name='End time')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubeops_api.Cluster')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.Script')),
                ('targets', models.ManyToManyField(to='kubeops_api.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
