# Generated by Django 2.1.2 on 2019-10-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20191017_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfsstorage',
            old_name='hosts',
            new_name='nfs_host',
        ),
    ]
