# Generated by Django 2.1.2 on 2019-10-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20191017_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfsstorage',
            name='allow_ip',
            field=models.CharField(default='0.0.0.0/0', max_length=128),
        ),
    ]
