# Generated by Django 2.1.2 on 2019-10-18 11:30

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20191018_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfsstorage',
            name='status',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('RUNNING', 'RUNNING'), ('ERROR', 'ERROR')], default='RUNNING', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='nfsstorage',
            name='vars',
            field=common.models.JsonDictTextField(default={'allow_ip': '0.0.0.0/0', 'storage_nfs_server_path': '/exports'}),
        ),
    ]
