# Generated by Django 2.1.2 on 2019-10-24 04:42

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20191018_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfsstorage',
            name='vars',
            field=common.models.JsonDictTextField(default={'allow_ip': '*', 'storage_nfs_server_path': '/exports'}),
        ),
    ]
