playbooks:
  - name:  config
    alias: config.yml
  - name:  prepare
    alias: prepare.yml
  - name:  master
    alias: master.yml
  - name:  worker
    alias: worker.yml
  - name:  addon
    alias: addon.yml
  - name:  bigip-config
    alias: f5-bigip.yml
  - name:  uninstall
    alias: clean.yml
  - name:  upgrade-worker
    alias: upgrade-worker.yml
  - name:  upgrade-master
    alias: upgrade-master.yml
  - name:  upgrade-addon
    alias: upgrade-addon.yml
  - name:  scale
    alias: scale.yml
  - name:  cluster-backup
    alias: cluster-backup.yml
  - name:  cluster-restore
    alias: cluster-restore.yml

operations:
  - name: install
    steps:
      - name: create-resource
        flow: 创建主机
      - name: config
        playbook: config
        flow: 配置操作系统
      - name: prepare
        playbook: prepare
        flow: 准备安装环境
      - name: master
        playbook: master
        flow: 安装 master
      - name: worker
        playbook: worker
        flow: 安装 worker
      - name: addon
        playbook: addon
        flow: 安装内置应用
  - name: uninstall
    steps:
      - name: uninstall
        playbook: uninstall
        flow: 卸载集群
  - name: bigip-config
    steps:
      - name: bigip-config
        playbook: bigip-config
        flow: 配置 F5

  - name: upgrade
    steps:
      - name: upgrade-worker
        playbook: upgrade-worker
        flow: 升级 worker
      - name: upgrade-master
        playbook: upgrade-master
        flow: 升级 master
      - name: upgrade-addon
        playbook: upgrade-addon
        flow: 升级内置应用

  - name: add-worker
    steps:
      - name: add-node
        flow: 添加节点
        playbook: scale

  - name: scale
    steps:
      - name: create-resource
        flow: 创建主机
      - name: scale
        flow: 伸缩
        playbook: scale

  - name: cluster-backup
    steps:
      - name: cluster-backup
        playbook: cluster-backup
        flow: 集群备份

  - name: cluster-restore
    steps:
      - name: cluster-restore
        playbook: cluster-restore
        flow: 集群备份恢复
roles:
  - name: cluster_nodes
    children:
      - master
      - worker
  - name: all_nodes
    children:
      - lb
      - daemon
      - cluster_nodes
  - name: kube-node
    children:
      - worker
  - name: kube-master
    children:
      - master
  - name: etcd
    children:
      - master
    meta:
      hidden: true
  - name: config
    children:
      - master
      - worker
      - lb
    meta:
      hidden: true

apps:
  - name: Dashboard
    logo: k8s.png
    url_key: dashboard
    describe: "Kubernetes 管理控制台"

  - name: Grafana
    logo: grafana_icon.svg
    url_key: grafana
    describe: "集群监控展示面板"

  - name: Prometheus
    logo: prometheus.ico
    url_key: prometheus
    describe: "集群监控采集工具"

  - name: Registry-console
    logo: registry.png
    url_key: registry-ui
    describe: "Docker 镜像仓库"

  - name: Traefik
    logo: traefik_logo.svg
    url_key: traefik
    describe: "HTTP 反向代理、负载均衡工具"

  - name: Weave Scope
    logo: weave-logo.png
    url_key: scope
    describe: "实时交互展示和管理 Kubernetes 集群、主机、Pod 和容器"

cluster_infos:
  - name: 网络插件
    key: CLUSTER_NETWORK
  - name: 网络模式
    key: FLANNEL_BACKEND
  - name: server_cidr
    key: SERVICE_CIDR
  - name: cluster_cidr
    key: CLUSTER_CIDR

networks:
  - name: flannel
    vars:
      CLUSTER_NETWORK: flannel
      flanneld_image: "quay.io/coreos/flannel"
      flanneld_version: "v0.11.0-amd64"
    configs:
      - name: FLANNEL_BACKEND
        alias: 网络模式
        type: Select
        value: vxlan
        required: true
        display: true
        options:
          - name: vxlan
            value: vxlan
          - name: host-gw
            value: host-gw
      - name: SERVICE_CIDR
        alias: Service CIDR
        value: 10.68.0.0/16
        type: Input
        required: true
        display: true
      - name: CLUSTER_CIDR
        type: Input
        alias: POD CIDR
        value: 172.20.0.0/16
        required: true
        display: true
  - name: calico
    vars:
      CLUSTER_NETWORK: calico
    configs:
      - name: SERVICE_CIDR
        alias: Service CIDR
        value: 10.68.0.0/16
        type: Input
        required: true
        display: true
      - name: CLUSTER_CIDR
        type: Input
        alias: POD CIDR
        value: 172.20.0.0/16
        required: true
        display: true

storages:
  - name: vsan
    deploy_type: ['AUTOMATIC']
    provider: ['vsphere']
    vars:
      storage_vsan_enabled: true
    configs:
      - name: set_vsan_default
        type: Switch
        alias: 默认存储
        value: true
        required: true
        display: true

  - name: nfs
    deploy_type: ['AUTOMATIC','MANUAL']
    provider: ['vsphere','openstack']
    vars:
      storage_nfs_enabled: true
      storage_nfs_provisioner_name: nfs-provisioner
    configs:
      - name: set_nfs_default
        type: Switch
        alias: 默认存储
        value: true
        required: true
        display: true


  - name: cinder
    deploy_type: ['AUTOMATIC']
    provider: ['openstack']
    vars:
      storage_cinder_enabled: true
    configs:
      - name: set_cinder_default
        type: Switch
        alias: 默认存储
        value: true
        required: true
        display: true


public_config:
  - name: APP_DOMAIN
    alias: 应用域名
    type: Input
    default: apps.$cluster_name$domain_suffix
    value:
    required: true
    help_text: 应用域名
    display: true

templates:
  - name: 一主多节点
    comment: '此部署模型为一主多节点部署模型，1个 Master 节点和至少1个 Worker 节点。'
    deploy_type: 'SINGLE'
    private_vars:
      DEPLOY_MODE: 'single-master'
      prometheus_install: true
      grafana_install: true
      kuberhealthy_install: true
      loki_install: true
    roles:
      - name: master
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
                - "7.7"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: worker
        children:
          - new_node
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
                - "7.7"
          node_vars: []
          requires:
            nodes_require:
              - '>'
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 32
                unit: "GB"
                comment: "无"
  - name: 多主多节点
    comment: '此部署模型为多主多节点部署模型，3个 Master 节点和至少1 个 Worker 节点。'
    deploy_type: 'MULTIPLE'
    private_vars:
      DEPLOY_MODE: 'multiple-master'
      prometheus_install: true
      grafana_install: true
      kuberhealthy_install: true
      loki_install: true
    roles:
      - name: master
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
                - "7.7"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 3
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: worker
        children:
          - new_node
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
                - "7.7"
          node_vars: []
          requires:
            nodes_require:
              - '>'
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 32
                unit: "GB"
                comment: "无"