ALTER TABLE ko_cluster_tool ADD COLUMN `higher_version` VARCHAR(255) NULL;

ALTER TABLE ko_cluster_manifest ADD COLUMN `tool_vars` mediumtext;

insert into `ko`.`ko_cluster_manifest`(`id`, `name`, `version`, `core_vars`, `network_vars`, `other_vars`, `created_at`, `updated_at`, `is_active`) VALUES (UUID(), 'v1.18.15-ko1', 'v1.18.15', '[{\"name\":\"kubernetes\",\"version\":\"v1.18.15\"},{\"name\":\"docker\",\"version\":\"19.03.9\"},{\"name\":\"etcd\",\"version\":\"v3.4.14\"},{\"name\":\"containerd\",\"version\":\"1.4.3\"}]', '[{\"name\":\"calico\",\"version\":\"v3.16.5\"},{\"name\":\"flanneld\",\"version\":\"v0.13.0\"}]', '[{\"name\":\"coredns\",\"version\":\"1.8.0\"},{\"name\":\"traefik\",\"version\":\"v2.2.1\"},{\"name\":\"ingress-nginx\",\"version\":\"0.33.0\"},{\"name\":\"metrics-server\",\"version\":\"v0.3.6\"},{\"name\":\"helm-v2\",\"version\":\"v2.17.0\"},{\"name\":\"helm-v3\",\"version\":\"v3.4.1\"}]', date_add(now(), interval 8 HOUR), date_add(now(), interval 8 HOUR), 1);

UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.0.0"},{"name":"kubeapps","version":"v1.10.2"},{"name":"prometheus","version":"v2.18.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.4-ko1';
UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.0.0"},{"name":"kubeapps","version":"v1.10.2"},{"name":"prometheus","version":"v2.18.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.6-ko1';
UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.0.0"},{"name":"kubeapps","version":"v1.10.2"},{"name":"prometheus","version":"v2.18.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.8-ko1';
UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.0.0"},{"name":"kubeapps","version":"v1.10.2"},{"name":"prometheus","version":"v2.18.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.10-ko1';
UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.0.0"},{"name":"kubeapps","version":"v1.10.2"},{"name":"prometheus","version":"v2.18.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.12-ko1';
UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.0.0"},{"name":"kubeapps","version":"v1.10.2"},{"name":"prometheus","version":"v2.18.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.14-ko1';
UPDATE ko_cluster_manifest SET tool_vars='[{"name":"dashboard","version":"v2.0.3"},{"name":"loki","version":"v2.1.0"},{"name":"kubeapps","version":"v2.0.1"},{"name":"prometheus","version":"v2.20.1"},{"name":"chartmuseum","version":"v0.12.0"},{"name":"registry","version":"v2.7.1"},{"name":"grafana","version":"v7.3.3"},{"name":"logging","version":"v7.6.2"}]' WHERE name='v1.18.15-ko1';