# Generated by Django 2.1.2 on 2019-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0006_auto_20190723_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='persistent_storage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
