# Generated by Django 2.1.2 on 2019-07-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0007_auto_20190724_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='template',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='StorageTemplate',
        ),
    ]
