# Generated by Django 2.1.2 on 2019-09-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0021_auto_20190903_1006'),
        ('kubeops_api', '0011_cluster_terraform_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostinfo',
            name='volumes',
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='memory',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='os_version',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='volumes',
            field=models.ManyToManyField(to='kubeops_api.Volume'),
        ),
        migrations.AddField(
            model_name='host',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_provider.Zone'),
        ),
        migrations.DeleteModel(
            name='HostInfo',
        ),
    ]
