# Generated by Django 2.1.2 on 2019-09-23 08:51

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0018_cluster_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployexecution',
            name='params',
            field=common.models.JsonDictTextField(default={}),
        ),
    ]
