# Generated by Django 2.1.2 on 2019-09-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0019_deployexecution_params'),
        ('kubeops_api', '0020_auto_20190920_0946'),
    ]

    operations = [
    ]
