# Generated by Django 2.1.11 on 2019-12-10 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kubeops_api', '0042_auto_20191111_1043'),
    ]

    def forwards_func(apps, schema_editor):
        Setting = apps.get_model("kubeops_api", "Setting")
        db_alias = schema_editor.connection.alias
        Setting.objects.using(db_alias).filter(key__contains="dns").delete()

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
