# Generated by Django 2.1.15 on 2019-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0043_auto_20191210_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=256)),
                ('reason', models.CharField(max_length=256)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='conditions',
            field=models.ManyToManyField(to='kubeops_api.Condition'),
        ),
    ]
