# Generated by Django 2.1.15 on 2019-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0045_auto_20191223_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='reason',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
