# Generated by Django 2.1.15 on 2019-12-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0047_auto_20191223_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCheck',
        ),
    ]
