# Generated by Django 2.1.15 on 2019-12-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0048_delete_healthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='conditions',
            field=models.ManyToManyField(to='kubeops_api.Condition'),
        ),
        migrations.AlterField(
            model_name='clusterhealthhistory',
            name='date_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('HOUR', 'HOUR')], default='HOUR', max_length=255),
        ),
    ]
