# Generated by Django 2.1.15 on 2019-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0052_auto_20191224_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterhealthhistory',
            name='date_type',
            field=models.CharField(choices=[('HOUR', 'HOUR'), ('DAY', 'DAY')], default='HOUR', max_length=255),
        ),
        migrations.AlterField(
            model_name='host',
            name='conditions',
            field=models.ManyToManyField(to='kubeops_api.Condition'),
        ),
        migrations.AlterField(
            model_name='node',
            name='conditions',
            field=models.ManyToManyField(to='kubeops_api.Condition'),
        ),
    ]
