# Generated by Django 2.1.15 on 2019-12-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0053_auto_20191224_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='gpu_info',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='gpu_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clusterhealthhistory',
            name='date_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('HOUR', 'HOUR')], default='HOUR', max_length=255),
        ),
    ]
