# Generated by Django 2.1.15 on 2020-01-06 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0054_auto_20191225_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='gpus',
            field=models.ManyToManyField(to='kubeops_api.GPU'),
        ),
    ]
