# Generated by Django 2.1.15 on 2020-01-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0055_auto_20200106_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='info',
            new_name='name',
        ),
    ]
