# Generated by Django 2.1.11 on 2020-02-10 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0056_auto_20200106_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4)),
                ('resource_id', models.UUIDField(default=uuid.uuid4)),
                ('resource_type', models.CharField(choices=[('CLUSTER', 'CLUSTER'), ('HOST', 'HOST'), ('PLAN', 'PLAN'), ('BACKUP_STORAGE', 'BACKUP_STORAGE'), ('STORAGE', 'STORAGE')], max_length=64)),
            ],
        )
    ]
