# Generated by Django 2.1.11 on 2020-02-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0057_auto_20200210_0605'),
    ]

    def forwards_func(apps, schema_editor):
        Item = apps.get_model("kubeops_api", "Item")
        db_alias = schema_editor.connection.alias
        Item.objects.using(db_alias).bulk_create([
            Item(name="KubeOperator",description="默认项目"),
        ])

    def reverse_func(apps, schema_editor):
        Item = apps.get_model("kubeops_api", "Item")
        db_alias = schema_editor.connection.alias
        Item.objects.using(db_alias).filter(name="KubeOperator").delete()

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
