# Generated by Django 2.2.10 on 2020-02-23 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200223_0731'),
        ('kubeops_api', '0064_auto_20200223_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=128, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubeops_api.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
