# Generated by Django 2.2.10 on 2020-02-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0066_auto_20200224_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrole',
            old_name='user',
            new_name='profile',
        ),
    ]
