# Generated by Django 2.2.10 on 2020-02-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200223_0731'),
        ('kubeops_api', '0067_auto_20200224_0258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemRole',
            new_name='ItemRoleMapping',
        ),
        migrations.AlterField(
            model_name='clusterhealthhistory',
            name='date_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('HOUR', 'HOUR')], default='HOUR', max_length=255),
        ),
    ]
