# Generated by Django 2.2.10 on 2020-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0070_auto_20200224_0741'),
        ('kubeops_api', '0070_upgrade_item_resource'),
    ]

    operations = [
    ]
