# Generated by Django 2.2.10 on 2020-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0072_merge_20200224_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='tab',
            field=models.CharField(default='system', max_length=128),
        ),
    ]
