# Generated by Django 2.2.10 on 2020-04-20 10:12

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('kubeops_api', '0075_auto_20200408_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CisLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=126, unique=True)),
                ('cluster_id', models.UUIDField(default=uuid.uuid4)),
                ('detail', common.models.JsonListTextField(default={})),
                ('result', common.models.JsonDictTextField(default={})),
                ('status', models.CharField(choices=[('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='FAILED',max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
