- name: 获取docker版本信息
  shell: "dockerd --version | awk '{print $3}' | sed s/,//"
  register: docker_ver

- block:
    - name: 下载新 docker 二进制文件
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
        - containerd
        - containerd-shim
        - docker-init
        - runc
        - docker
        - ctr
        - dockerd
        - docker-proxy
      notify:
        restart_docker
  when: 'docker_ver.stdout < docker_version'

- name: 获取 registry 信息
  shell: "cat /etc/docker/daemon.json"
  register: daemon

- name: 添加 registry
  shell: sed -i 's/"]/","{{registry_prefix}}:{{registry_port}}"]/g' /etc/docker/daemon.json
  when: 'registry not in daemon.stdout'

- name: 添加 kubeapps registry
  shell: sed -i 's/"]/","{{ kubeapps_registry_hostname }}"]/g' /etc/docker/daemon.json
  when:
    - 'kubeapps_install is defined'
    - 'kubeapps_install'
    - 'kubeapps_registry_hostname not in daemon.stdout'

- name: restart_docker
  service:
    name: "docker"
    state: restarted
  when: 'registry not in daemon.stdout or (kubeapps_install is defined and kubeapps_install and kubeapps_registry_hostname not in daemon.stdout)'

- name: 获取 kube-master 版本信息
  shell: "kubectl version --short | grep Server | awk '{print $3}' | tr -d 'a-zA-Z'"
  register: kube_ver

- block:
    - name: 下载 kube-master 二进制
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
        - kubectl
        - kubelet
        - kube-proxy
      notify:
        restart_master

    - name: 以轮询的方式等待master服务启动完成
      command: "{{ bin_dir }}/kubectl get node"
      register: result
      until:    result.rc == 0
      retries: 15
      delay: 5
      run_once: True
  when: 'kube_ver.stdout < kube_version'
