# Generated by Django 2.2.10 on 2020-02-23 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kubeops_api', '0062_auto_20200221_0510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('current_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_item', to='kubeops_api.Item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
