# Generated by Django 2.2.10 on 2020-02-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0062_auto_20200221_0510'),
        ('users', '0002_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_item', to='kubeops_api.Item'),
        ),
    ]
