# Generated by Django 2.2.10 on 2020-02-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
    ]
