# Generated by Django 2.2.10 on 2020-03-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200223_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_item',
        ),
    ]
