# Generated by Django 2.2.10 on 2020-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_current_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.CharField(choices=[('ldap', 'ldap'), ('local', 'local')], default='local', max_length=128),
        ),
    ]
