# Generated by Django 2.1.2 on 2018-11-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='rel_path',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='playbook',
            old_name='times',
            new_name='execute_times',
        ),
        migrations.AlterUniqueTogether(
            name='playbookexecution',
            unique_together={('playbook', 'num')},
        ),
    ]
