# Generated by Django 2.1.2 on 2018-11-05 04:23

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0003_auto_20181105_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbookexecution',
            name='result',
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='result_raw',
            field=common.models.JsonDictTextField(blank=True, default='{}', null=True, verbose_name='Result raw'),
        ),
        migrations.AddField(
            model_name='playbookexecution',
            name='result_summary',
            field=common.models.JsonDictTextField(blank=True, default='{}', null=True, verbose_name='Result summary'),
        ),
    ]
