# Generated by Django 2.1.2 on 2018-11-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0004_auto_20181105_0423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbookexecution',
            unique_together=set(),
        ),
    ]
