# Generated by Django 2.1.2 on 2018-11-05 06:50

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0005_auto_20181105_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocexecution',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='adhocexecution',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='adhocexecution',
            name='is_success',
        ),
        migrations.RemoveField(
            model_name='adhocexecution',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='adhocexecution',
            name='summary',
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='result_raw',
            field=common.models.JsonDictTextField(blank=True, default='{}', null=True, verbose_name='Result raw'),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='result_summary',
            field=common.models.JsonDictTextField(blank=True, default='{}', null=True, verbose_name='Result summary'),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='adhocexecution',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='adhocexecution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='playbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='ansible_api.Playbook'),
        ),
    ]
