# Generated by Django 2.1.2 on 2018-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0006_auto_20181105_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoc',
            name='execute_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
