# Generated by Django 2.1.2 on 2018-11-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0007_auto_20181105_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='pull_policy',
            field=models.CharField(choices=[('if_not_present', 'Always'), ('always', 'If not present'), ('never', 'Never')], default='if_not_present', max_length=16),
        ),
    ]
