# Generated by Django 2.1.2 on 2019-10-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ansible_api', '0002_auto_20190305_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfsStorage',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Project')),
                ('server', models.CharField(max_length=128, null=True)),
                ('path', models.CharField(max_length=128, null=True)),
                ('status', models.CharField(choices=[('CREATING', 'CREATING'), ('RUNNING', 'RUNNING')], max_length=128, null=True)),
            ],
            bases=('ansible_api.project',),
        ),
    ]
