# Generated by Django 2.1.2 on 2019-10-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0033_auto_20191017_0234'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfsstorage',
            name='hosts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kubeops_api.Host'),
        ),
        migrations.AddField(
            model_name='nfsstorage',
            name='option',
            field=models.CharField(choices=[('NEW', 'NEW'), ('EXISTS', 'EXISTS')], max_length=128, null=True),
        ),
    ]
