# Generated by Django 2.1.2 on 2019-10-18 09:11

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_nfsstorage_allow_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfsstorage',
            name='allow_ip',
        ),
        migrations.RemoveField(
            model_name='nfsstorage',
            name='nfs_host',
        ),
        migrations.RemoveField(
            model_name='nfsstorage',
            name='option',
        ),
        migrations.RemoveField(
            model_name='nfsstorage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='nfsstorage',
            name='server',
        ),
        migrations.AddField(
            model_name='nfsstorage',
            name='vars',
            field=common.models.JsonDictTextField(default={'allow_ip': '0.0.0.0/0', 'path': '/exports'}),
        ),
    ]
