# Generated by Django 2.1.11 on 2019-12-06 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_cephstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterCephStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.UUIDField(default=uuid.uuid4)),
                ('ceph_storage_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
