# Generated by Django 2.1.2 on 2018-12-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0007_auto_20181207_0429'),
        ('ansible_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Group',
            name='hosts',
            field=models.ManyToManyField(related_name='groups', to='ansible_api.Host'),
        ),
    ]
