# Generated by Django 2.1.2 on 2019-01-04 04:08

import common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocexecution',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='adhocexecution',
            name='result_raw',
            field=common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Result raw'),
        ),
        migrations.AlterField(
            model_name='adhocexecution',
            name='result_summary',
            field=common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Result summary'),
        ),
        migrations.AlterField(
            model_name='clustergroup',
            name='name',
            field=models.CharField(choices=[('master', 'master'), ('node', 'node'), ('etcd', 'etcd')], max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a valid name consisting of Unicode letters, numbers, underscores, or hyphens, or dot', regex='^[a-zA-Z0-9_\\-\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('master', 'master'), ('node', 'node'), ('etcd', 'etcd')], max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a valid name consisting of Unicode letters, numbers, underscores, or hyphens, or dot', regex='^[a-zA-Z0-9_\\-\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='result_raw',
            field=common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Result raw'),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='result_summary',
            field=common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Result summary'),
        ),
    ]
