# Generated by Django 2.1.2 on 2019-02-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0002_auto_20190218_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ansible_api.Project'),
        ),
    ]
