# Generated by Django 2.1.2 on 2019-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0002_auto_20190104_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='pull_policy',
            new_name='update_policy',
        ),
        migrations.AlterField(
            model_name='playbook',
            name='type',
            field=models.CharField(choices=[('json', 'json'), ('text', 'text'), ('file', 'file'), ('git', 'git'), ('http', 'http'), ('local', 'local')], default='json', max_length=16),
        ),
    ]
