# Generated by Django 2.1.2 on 2018-12-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0010_auto_20181207_0656'),
        ('ansible_api', '0002_auto_20181207_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Group',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='ansible_api.Group'),
        ),
    ]
