# Generated by Django 2.1.2 on 2019-02-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0003_auto_20190219_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_api.Project'),
        ),
    ]
