resource: kubernetes-1.15.0
version: 1.15.0
components:
  kubernetes: 1.15.0
  etcd: 3.3.10
  docker: docker-ce-18.09.2
images:
  - name: quay.io/external_storage/nfs-client-provisioner
    tag: v3.1.0-k8s1.11
  - name: docker.io/traefik
    tag: v1.7.11
  - name: docker.io/grafana/grafana
    tag: 5.2.1
  - name: quay.io/prometheus/alertmanager
    tag: v0.15.2
  - name: docker.io/busybox
    tag: 1.31.0
  - name: quay.io/prometheus/node-exporter
    tag: v0.15.2
  - name: quay.io/prometheus/prometheus
    tag: v2.4.3
  - name: quay.io/prometheus/pushgateway
    tag: v0.5.2
  - name: docker.io/coredns/coredns
    tag: 1.5.0
  - name: quay.io/coreos/flannel
    tag: v0.11.0-amd64
  - name: gcr.io/google_containers/heapster-grafana-amd64
    tag: v4.4.3
  - name: gcr.io/google_containers/heapster-amd64
    tag: v1.5.4
  - name: gcr.io/google_containers/heapster-influxdb-amd64
    tag: v1.5.2
  - name: gcr.io/kubernetes-helm/tiller
    tag: v2.12.3
  - name: k8s.gcr.io/kubernetes-dashboard-amd64
    tag: v1.10.0
  - name: k8s.gcr.io/metrics-server-amd64
    tag: v0.3.2
  - name: quay.io/coreos/configmap-reload
    tag: v0.0.1
  - name: gcr.io/google-containers/pause-amd64
    tag: 3.1
  - name: docker.io/registry
    tag: 2
  - name: docker.io/alpine
    tag: 3.6
  - name: quay.io/coreos/kube-state-metrics
    tag: v1.4.0
  - name: appropriate/curl
    tag: edge
  - name: docker.io/konradkleine/docker-registry-frontend
    tag: v2
  - name: docker.io/weaveworks/scope:1.9.1
    tag: 1.9.1
  - name: calico/node
    tag: v3.4.4
  - name: calico/cni
    tag: v3.4.4
  - name: calico/kube-controllers
    tag: v3.4.4

playbooks:
  - name:  config
    alias: kubeasz/config.yml
  - name:  prepare
    alias: kubeasz/prepare.yml
  - name:  master
    alias: kubeasz/master.yml
  - name:  worker
    alias: kubeasz/worker.yml
  - name:  addon
    alias: kubeasz/addon.yml
  - name:  bigip-config
    alias: kubeasz/f5-bigip.yml
  - name:  uninstall
    alias: kubeasz/clean.yml

operations:
  - name: install
    steps:
      - name: create-resource
        flow: 创建资源
      - name: config
        playbook: config
        flow: 配置操作系统
      - name: prepare
        playbook: prepare
        flow: 准备安装环境
      - name: master
        playbook: master
        flow: 安装 master
      - name: worker
        playbook: worker
        flow: 安装 worker
      - name: addon
        playbook: addon
        flow: 安装内置应用
  - name: uninstall
    steps:
      - name: uninstall
        playbook: uninstall
        flow: 卸载集群
  - name: bigip-config
    steps:
      - name: bigip-config
        playbook: bigip-config
        flow: 配置 F5

roles:
  - name: new_node
  - name: cluster_nodes
    children:
      - master
      - worker
  - name: all_nodes
    children:
      - lb
      - daemon
      - cluster_nodes
  - name: kube-node
    children:
      - worker
  - name: kube-master
    children:
      - master
  - name: etcd
    children:
      - master
    meta:
      hidden: true
  - name: config
    children:
      - master
      - worker
      - daemon
      - lb
    meta:
      hidden: true
    vars:
      bin_dir: "/usr/local/bin"
      ca_dir: "/etc/kubernetes/ssl"
      CONTAINER_RUNTIME: "docker"
      NODE_PORT_RANGE: "30000-32767"
      CLUSTER_KUBERNETES_SVC_IP: "10.68.0.1"
      CLUSTER_DNS_SVC_IP: "10.68.0.2"
      CLUSTER_DNS_DOMAIN: "cluster.local."
      #kubeOperator
      base_dir: "/opt/kubeOperator-kube-bin/1.15.0"
      kube_version: "1.15.0"
      repo_port: 8082
      registry_prefix: "registry.kubeops.io:8092"
      download_path: "repository/raw/1.15.0/k8s.1-15-0.tar.gz"
      file_name: "k8s.1-15-0.tar.gz"

      #dns
      dns_install: true
      dns_image: "docker.io/coredns/coredns"
      dns_version: "1.5.0"

      #metrics-server
      metricsserver_install: false
      metricsserver_image: "k8s.gcr.io/metrics-server-amd64"
      metricsserver_version: "v0.3.2"

      #dashboard
      dashboard_install: true
      dashboard_image: "k8s.gcr.io/kubernetes-dashboard-amd64"
      dashboard_version: "v1.10.0"

      #heapster
      heapster_install: true
      heapster_version: "v1.5.4"
      heapster_image: "gcr.io/google_containers/heapster-amd64"

      #traefik
      traefik_version: "v1.7.11"
      traefik_image: "docker.io/traefik"

      #efk
      efk_install: false
      #helm
      helm_namespace: kube-system
      helm_cert_cn: helm001
      tiller_sa: tiller
      tiller_cert_cn: tiller001
      tiller_image: "gcr.io/kubernetes-helm/tiller"
      tiller_version: "v2.12.3"

      #flannel
      NODE_WITH_MULTIPLE_NETWORKS: "true"
      flanneld_image: "quay.io/coreos/flannel"
      flanneld_version: "v0.11.0-amd64"

      #registry
      REGISTRY_ACCOUNT_NAME: admin
      REGISTRY_ACCOUNT_PASSWORD: admin123
      IMAGE_PULL_SECRET: registry-fit2cloud-com-key

apps:
  - name: Dashboard
    logo: k8s.png
    url_key: dashboard
    describe: "Kubernetes 管理控制台"

  - name: Grafana
    logo: grafana_icon.svg
    url_key: grafana
    describe: "集群监控展示面板"

  - name: Prometheus
    logo: prometheus.ico
    url_key: prometheus
    describe: "集群监控采集工具"

  - name: Registry-console
    logo: registry.png
    url_key: registry-ui
    describe: "Docker 镜像仓库"

  - name: Traefik
    logo: traefik_logo.svg
    url_key: traefik
    describe: "HTTP 反向代理、负载均衡工具"

  - name: Weave Scope
    logo: weave-logo.png
    url_key: scope
    describe: "实时交互展示和管理 Kubernetes 集群、主机、Pod 和容器"

cluster_infos:
  - name: 网络插件
    key: CLUSTER_NETWORK
  - name: 网络模式
    key: FLANNEL_BACKEND
  - name: server_cidr
    key: SERVICE_CIDR
  - name: cluster_cidr
    key: CLUSTER_CIDR

networks:
  - name: flannel
    vars:
      CLUSTER_NETWORK: flannel
      flanneld_image: "quay.io/coreos/flannel"
      flanneld_version: "v0.11.0-amd64"
    configs:
      - name: FLANNEL_BACKEND
        alias: 网络模式
        type: Select
        value: vxlan
        required: true
        display: true
        options:
          - name: vxlan
            value: vxlan
          - name: host-gw
            value: host-gw
      - name: SERVICE_CIDR
        alias: Service CIDR
        value: 10.68.0.0/16
        type: Input
        required: true
        display: true
      - name: CLUSTER_CIDR
        type: Input
        alias: POD CIDR
        value: 172.20.0.0/16
        required: true
        display: true
  - name: calico
    vars:
      CLUSTER_NETWORK: calico
    configs:
      - name: SERVICE_CIDR
        alias: Service CIDR
        value: 10.68.0.0/16
        type: Input
        required: true
        display: true
      - name: CLUSTER_CIDR
        type: Input
        alias: POD CIDR
        value: 172.20.0.0/16
        required: true
        display: true

storages:
  - name: vsan
    vars:
      storage_vsan_enabled: true
    configs:
      - name: set_vsan_default
        type: Switch
        alias: 默认存储
        value: true
        required: true
        display: true

  - name: nfs
    vars:
      storage_nfs_enabled: true
      storage_nfs_storage_class: nfs-storage
      storage_nfs_provisioner_name: nfs-provisioner
    configs:
      - name: storage_nfs_server
        alias: NFS 地址
        comment: nfs_server
        value: 10.0.0.1
        type: Input
        required: true
        display: true
      - name: storage_nfs__server_path
        type: Input
        alias: NFS 路径
        comment: nfs_path
        value: /exports
        required: true
        display: true
      - name: set_nfs_default
        type: Switch
        alias: 默认存储
        value: true
        required: true
        display: true



public_config:
  - name: APP_DOMAIN
    alias: 应用域名
    type: Input
    default: apps.$cluster_name$domain_suffix
    value:
    required: true
    help_text: 应用域名
    display: true

templates:
  - name: 一主多节点
    comment: '此部署模型为一主多节点部署模型，1个daemon 节点,1个 Master 节点和至少3个 Worker 节点。'
    deploy_type: 'SINGLE'
    private_vars:
      DEPLOY_MODE: 'single-master'
      prometheus_install: true
      grafana_install: true
    roles:
      - name: master
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: daemon
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 1
                excellent: 2
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 2
                excellent: 4
                unit: "GB"
                comment: "无"
      - name: worker
        children:
          - new-node
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '>'
              - 3
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 32
                unit: "GB"
                comment: "无"
  - name: 多主多节点
    comment: '此部署模型为多主多节点部署模型，1个daemon 节点,3个 Master 节点和至少3个 Worker 节点。'
    deploy_type: 'MULTIPLE'
    private_vars:
      DEPLOY_MODE: 'multiple-master'
      prometheus_install: true
      grafana_install: true
    roles:
      - name: master
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: daemon
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 1
                excellent: 2
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 2
                excellent: 4
                unit: "GB"
                comment: "无"
      - name: worker
        children:
          - new_node
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '>'
              - 3
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 32
                unit: "GB"
                comment: "无"
