# Generated by Django 2.1.11 on 2019-12-05 04:06

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20191024_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CephStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('vars', common.models.JsonDictTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
