# Generated by Django 2.1.2 on 2019-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0002_auto_20190621_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('INSTALLING', 'installing'), ('READY', 'ready'), ('ERROR', 'error'), ('WARNING', 'warning')], default='READY', max_length=128),
        ),
    ]
