# Generated by Django 2.1.2 on 2019-07-10 02:50

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0004_auto_20190708_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('meta', common.models.JsonCharField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='health_checks',
            field=models.ManyToManyField(to='kubeops_api.NodeHealthCheck'),
        ),
    ]
