# Generated by Django 2.1.2 on 2019-07-10 09:34

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0005_auto_20190710_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('info', common.models.JsonDictTextField(blank=True, null=True)),
                ('conditions', common.models.JsonListTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
                'get_latest_by': 'date_created',
            },
        ),
        migrations.RemoveField(
            model_name='node',
            name='health_checks',
        ),
        migrations.DeleteModel(
            name='NodeHealthCheck',
        ),
        migrations.AddField(
            model_name='node',
            name='node_infos',
            field=models.ManyToManyField(to='kubeops_api.NodeInfo'),
        ),
    ]
