# Generated by Django 2.1.2 on 2019-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0005_auto_20190723_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('invalid', 'invalid'), ('valid', 'valid'), ('unknown', 'unknown')], default='unknown', max_length=128),
        ),
    ]
