# Generated by Django 2.1.2 on 2019-07-11 07:53

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0006_auto_20190710_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='components',
            field=common.models.JsonDictTextField(blank=True, null=True),
        ),
    ]
