# Generated by Django 2.1.2 on 2019-07-11 09:47

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0007_cluster_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_infos',
        ),
        migrations.AddField(
            model_name='node',
            name='info',
            field=common.models.JsonDictTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NodeInfo',
        ),
    ]
