# Generated by Django 2.1.2 on 2019-07-12 02:11

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0009_remove_node_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='metrics',
            field=common.models.JsonDictTextField(blank=True, null=True),
        ),
    ]
