# Generated by Django 2.1.2 on 2019-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0015_terraformhost'),
        ('kubeops_api', '0010_cluster_deploy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='terraform_hosts',
            field=models.ManyToManyField(to='cloud_provider.TerraformHost'),
        ),
    ]
