# Generated by Django 2.1.2 on 2019-07-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0010_node_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='components',
        ),
    ]
