# Generated by Django 2.1.2 on 2019-07-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0011_remove_cluster_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='metrics',
        ),
        migrations.AddField(
            model_name='cluster',
            name='network_plugin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
