# Generated by Django 2.1.2 on 2019-07-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0012_auto_20190715_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='config_path',
        ),
    ]
