# Generated by Django 2.1.2 on 2019-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0013_remove_cluster_config_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagetemplate',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='名称'),
        ),
    ]
