# Generated by Django 2.1.2 on 2019-07-22 04:52

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0014_auto_20190718_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField(allow_unicode=True, max_length=128, unique=True, verbose_name='Name')),
                ('username', models.CharField(default='root', max_length=256)),
                ('password', common.models.EncryptCharField(blank=True, max_length=4096, null=True)),
                ('private_key', common.models.EncryptCharField(blank=True, max_length=8192, null=True)),
            ],
        ),
    ]
