# Generated by Django 2.1.2 on 2019-07-22 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0015_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
