# Generated by Django 2.1.2 on 2019-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0016_credential_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('password', 'password'), ('password', 'private_key')], default='password', max_length=128),
        ),
    ]
