# Generated by Django 2.1.2 on 2019-09-19 10:18

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0016_backup_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('credentials', common.models.JsonDictTextField(default={})),
                ('type', models.CharField(choices=[('S3', 'S3'), ('OSS', 'OSS')], max_length=64)),
                ('status', models.CharField(choices=[('VALID', 'valid'), ('INVALID', 'invalid')], default='VALID', max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.DeleteModel(
            name='backup_storage',
        ),
    ]
