# Generated by Django 2.1.2 on 2019-09-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0016_backup_storage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='backup_storage',
            new_name='BackupStorage',
        ),
    ]
