# Generated by Django 2.1.2 on 2019-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0017_auto_20190919_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupstorage',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
    ]
