# Generated by Django 2.1.2 on 2019-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0017_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('password', 'password'), ('password', 'privateKey')], default='password', max_length=128),
        ),
    ]
