# Generated by Django 2.1.2 on 2019-07-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0019_auto_20190722_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kubeops_api.Credential'),
        ),
    ]
