# Generated by Django 2.1.2 on 2019-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0017_auto_20190919_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupstorage',
            name='type',
            field=models.CharField(choices=[('S3', 'S3'), ('OSS', 'OSS'), ('AZURE', 'AZURE')], max_length=64),
        ),
    ]
