# Generated by Django 2.1.2 on 2019-09-25 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0022_auto_20190923_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cron', models.IntegerField(max_length=64)),
                ('save_num', models.IntegerField(max_length=64)),
                ('project_id', models.CharField(max_length=64)),
                ('backup_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kubeops_api.BackupStorage')),
            ],
        ),
    ]
