# Generated by Django 2.1.2 on 2019-09-26 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0022_auto_20190923_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cron', models.IntegerField(default=0)),
                ('save_num', models.IntegerField(default=0)),
                ('backup_storage_id', models.CharField(blank=True, max_length=64, null=True)),
                ('project_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField(default=0, max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(max_length=256)),
                ('folder', models.CharField(max_length=64)),
                ('backup_storage_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
