# Generated by Django 2.1.2 on 2019-09-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0023_backupstrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupstrategy',
            name='cron',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backupstrategy',
            name='save_num',
            field=models.IntegerField(default=0),
        ),
    ]
