# Generated by Django 2.1.2 on 2019-09-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0024_auto_20190925_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupstrategy',
            name='backup_storage',
        ),
        migrations.AddField(
            model_name='backupstrategy',
            name='backup_storage_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
