# Generated by Django 2.1.2 on 2019-10-08 02:45

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0024_auto_20190927_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='auto_gather_info',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='password',
            field=common.models.EncryptCharField(blank=True, default='KubeOperator@2019', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('VALID', 'valid'), ('INVALID', 'invalid'), ('CREATING', 'creating'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=128),
        ),
    ]
