# Generated by Django 2.1.2 on 2019-10-10 03:10

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0027_package_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupstrategy',
            name='status',
            field=models.CharField(choices=[('ENABLE', 'Enable'), ('ENABLE', 'Disable')], default='ENABLE', max_length=64),
        ),
        migrations.AlterField(
            model_name='clusterbackup',
            name='size',
            field=models.IntegerField(default=0),
        )
    ]
