# Generated by Django 2.1.2 on 2019-10-11 03:58

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0028_auto_20191010_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='endpoint',
        ),
        migrations.AlterField(
            model_name='package',
            name='meta',
            field=common.models.JsonTextField(blank=True, null=True, verbose_name='Meta'),
        ),
    ]
