# Generated by Django 2.1.2 on 2019-10-11 08:25

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0028_auto_20191010_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('INSTALLING', 'installing'), ('DELETING', 'deleting'), ('READY', 'ready'), ('ERROR', 'error'), ('WARNING', 'warning'), ('UPGRADING', 'upgrading'), ('SCALING', 'scaling'), ('RESTORING', 'restoring')], default='READY', max_length=128),
        )
    ]
