# Generated by Django 2.1.2 on 2019-10-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0030_auto_20191015_0725'),
        ('kubeops_api', '0029_auto_20191011_0358'),
    ]

    operations = [
    ]
