# Generated by Django 2.1.2 on 2019-10-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0032_auto_20191016_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='node',
        ),
        migrations.AlterField(
            model_name='clusterhealthhistory',
            name='date_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('HOUR', 'HOUR')], default='HOUR', max_length=255),
        ),
    ]
