# Generated by Django 2.1.2 on 2019-10-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0035_auto_20191030_0703'),
        ('kubeops_api', '0035_auto_20191031_0415'),
    ]

    operations = [
    ]
