# Generated by Django 2.1.2 on 2019-10-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0036_auto_20191031_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='auth_template',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('INSTALLING', 'installing'), ('DELETING', 'deleting'), ('READY', 'ready'), ('ERROR', 'error'), ('WARNING', 'warning'), ('UPGRADING', 'upgrading'), ('SCALING', 'scaling'), ('RESTORING', 'restoring'), ('ADDING', 'adding'), ('BACKUP', 'backup')], default='READY', max_length=128),
        ),
        migrations.AlterField(
            model_name='clusterhealthhistory',
            name='date_type',
            field=models.CharField(choices=[('HOUR', 'HOUR'), ('DAY', 'DAY')], default='HOUR', max_length=255),
        ),
        migrations.DeleteModel(
            name='AuthTemplate',
        ),
    ]
