# Generated by Django 2.1.11 on 2019-11-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0041_auto_20191106_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DNS',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='order',
        ),
    ]
