# Generated by Django 2.1.2 on 2019-07-30 02:39

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0002_cloudprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('vars', common.models.JsonDictTextField(default={})),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_provider.CloudProviderTemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='cloudprovider',
            name='template',
        ),
        migrations.DeleteModel(
            name='CloudProvider',
        ),
    ]
