# Generated by Django 2.1.2 on 2019-07-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0005_auto_20190730_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cloud_region',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
