# Generated by Django 2.1.2 on 2019-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0008_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='ip_end',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='ip_start',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
