# Generated by Django 2.1.2 on 2019-08-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0011_auto_20190801_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='deploy_template',
            field=models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], default='single', max_length=128),
        ),
    ]
