# Generated by Django 2.1.2 on 2019-08-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0015_terraformhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformhost',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kubeops_api.Host'),
        ),
    ]
