# Generated by Django 2.1.2 on 2019-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0020_auto_20190903_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='zones',
            field=models.ManyToManyField(related_name='zones', to='cloud_provider.Zone'),
        ),
    ]
