---

# 修改安装rpm源
- name: Replace repos.
  hosts: all_nodes
  roles:
    - replace_repos

# 提前安装好dnsmasq
- name: Preinstall dnsmasq except dbus error
  hosts: OSEv3
  roles:
    - add_hosts_dnsmasq

# 初始化防火墙端口
- name: Initialize firewall check
  hosts: nodes
  vars:
    firewall_ports:
      - 4789
      - 8443
      - 80
      - 443
      - 53
      - 10250
      - 2049
      - 2379
      - 2380
      - 4001
      - 4789
      - 9000
      - 1936
      - 9200
      - 9300
      - 123
  gather_facts: no
  roles:
    - check_firewall_initialize