# Generated by Django 2.1.11 on 2019-11-11 04:19

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('deploy_template', models.CharField(choices=[('SINGLE', 'single'), ('MULTIPLE', 'multiple')], default='SINGLE', max_length=128)),
                ('vars', common.models.JsonDictTextField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('cloud_region', models.CharField(default=None, max_length=128, null=True)),
                ('vars', common.models.JsonDictTextField(default={})),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Comment')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_provider.CloudProviderTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('vars', common.models.JsonDictTextField(default={})),
                ('cloud_zone', models.CharField(default=None, max_length=128, null=True)),
                ('ip_used', common.models.JsonListTextField(default=[], null=True)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('INITIALIZING', 'INITIALIZING'), ('ERROR', 'ERROR')], max_length=64, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_provider.Region')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_provider.Region'),
        ),
        migrations.AddField(
            model_name='plan',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_provider.Zone'),
        ),
        migrations.AddField(
            model_name='plan',
            name='zones',
            field=models.ManyToManyField(related_name='zones', to='cloud_provider.Zone'),
        ),
    ]
