# Generated by Django 2.1.2 on 2019-07-29 10:54

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('vars', common.models.JsonDictTextField(default={})),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_provider.CloudProviderTemplate')),
            ],
        ),
    ]
