# Generated by Django 2.1.2 on 2019-07-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0004_region_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='connected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='msg',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
