# Generated by Django 2.1.2 on 2019-07-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0006_region_cloud_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='connected',
        ),
        migrations.RemoveField(
            model_name='region',
            name='msg',
        ),
    ]
