# Generated by Django 2.1.2 on 2019-08-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0009_auto_20190731_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='ip_end',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='ip_start',
        ),
    ]
