# Generated by Django 2.1.2 on 2019-08-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0013_remove_plan_deploy_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='zones',
        ),
        migrations.AddField(
            model_name='plan',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_provider.Zone'),
        ),
    ]
