# Generated by Django 2.1.2 on 2019-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0016_auto_20190820_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('READY', 'READY'), ('INITIALIZING', 'INITIALIZING'), ('ERROR', 'ERROR')], max_length=64, null=True),
        ),
    ]
