# Generated by Django 2.1.2 on 2019-08-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0017_zone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformhost',
            name='folder',
        ),
    ]
