# Generated by Django 2.1.2 on 2019-09-03 10:06

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0019_auto_20190903_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformhost',
            name='zone',
        ),
        migrations.AddField(
            model_name='terraformhost',
            name='zone_vars',
            field=common.models.JsonDictTextField(default={}),
        ),
    ]
