- name: 获取 etcd 版本信息
  shell: "etcd --version | grep 'etcd Version'|awk '{print $3}'"
  register: etcd_ver

- block:
    - name: 下载etcd二进制文件
      copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
        - etcd
        - etcdctl

    - name: 开机启用etcd服务
      shell: systemctl enable etcd

    - name: 开启etcd服务
      shell: systemctl daemon-reload && systemctl restart etcd

    - name: 以轮询的方式等待服务同步完成
      shell: "systemctl status etcd.service|grep Active"
      register: etcd_status
      until: '"running" in etcd_status.stdout'
      retries: 15
      delay: 8

  when: 'etcd_ver.stdout < etcd_version'