- hosts: kube-node
  roles:
    - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }

- hosts:
    - kube-master
    - kube-node
    - { role: gpu-driver, when: "has_gpu is defined and has_gpu" }
    - { role: gpu-docker, when: "has_gpu is defined and has_gpu" }
  roles:
    - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
    - coredns