# Generated by Django 2.1.2 on 2018-12-06 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('branch', models.CharField(default='master', max_length=128, verbose_name='Branch')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='IsActive')),
            ],
        ),
    ]
