# Generated by Django 2.1.2 on 2019-01-04 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
    ]
