# Generated by Django 2.1.2 on 2018-12-06 08:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0001_initial'),
        ('openshift_api', '0002_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployexecution',
            name='project',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a87cb391-18e3-4e7f-b86f-81bde6583118'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('offline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='openshift_api.Offline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_api.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='DeployExecution',
        ),
    ]
