# Generated by Django 2.1.2 on 2019-01-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0003_auto_20190104_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployexecution',
            name='package',
        ),
    ]
