# Generated by Django 2.1.2 on 2018-12-06 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0001_initial'),
        ('openshift_api', '0003_auto_20181206_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ansible_api.host',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ansible_api.group',),
        ),
        migrations.AddField(
            model_name='cluster',
            name='config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cluster',
            name='status',
            field=models.CharField(default='idle', max_length=128),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('610a0e1a-44a2-4240-983d-770ba042b3ee'), primary_key=True, serialize=False),
        ),
    ]
