# Generated by Django 2.1.2 on 2019-01-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0004_remove_deployexecution_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_api.Project'),
        ),
    ]
