# Generated by Django 2.1.2 on 2019-02-18 03:21

from django.db import migrations


def forwards_func(apps, schema_editor):
    Cluster = apps.get_model("openshift_api", "Cluster")
    db_alias = schema_editor.connection.alias
    Cluster.objects.using(db_alias).create(name="default", is_super=True)


def reverse_func(apps, schema_editor):
    Cluster = apps.get_model("openshift_api", "Cluster")
    db_alias = schema_editor.connection.alias
    Cluster.objects.using(db_alias).filter(name="default").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('openshift_api', '0004_cluster_is_super'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
