# Generated by Django 2.1.2 on 2018-12-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0004_auto_20181206_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb8d0bfb-0548-4661-a4a3-7c65030c2f8c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='offline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='openshift_api.Offline'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ansible_api.Project'),
        ),
    ]
