# Generated by Django 2.1.2 on 2019-02-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0001_initial'),
        ('openshift_api', '0005_auto_20190218_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Host')),
            ],
            options={
                'abstract': False,
            },
            bases=('ansible_api.host',),
        ),
    ]
