# Generated by Django 2.1.2 on 2018-12-06 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0005_auto_20181206_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3b369d6-4fff-4aec-b0d3-06d211296b8e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='offline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='openshift_api.Offline'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_api.Project'),
        ),
    ]
