# Generated by Django 2.1.2 on 2018-12-07 04:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0001_initial'),
        ('openshift_api', '0006_auto_20181206_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6535079b-75dd-456a-b2fd-d53659c270f8'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Host')),
            ],
            options={
                'abstract': False,
            },
            bases=('ansible_api.host',),
        ),
    ]
