# Generated by Django 2.1.2 on 2019-02-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0007_auto_20190218_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='os_version',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='node',
            name='os',
            field=models.CharField(default='', max_length=128),
        ),
    ]
