# Generated by Django 2.1.2 on 2018-12-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0007_auto_20181207_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='offline',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='project',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
