# Generated by Django 2.1.2 on 2019-02-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0002_auto_20190218_0750'),
        ('openshift_api', '0008_auto_20190218_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openshift_api.Node')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ansible_api.Project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='ansible_api.Project')),
            ],
        ),
    ]
