# Generated by Django 2.1.2 on 2019-03-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0008_auto_20190319_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='host',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='openshift_api.Host'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='size',
            field=models.CharField(max_length=16),
        ),
    ]
