# Generated by Django 2.1.2 on 2019-03-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0009_auto_20190319_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='openshift_api.Host'),
        ),
    ]
