# Generated by Django 2.1.2 on 2018-12-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0002_auto_20181207_0429'),
        ('openshift_api', '0009_cluster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Group')),
            ],
            options={
                'abstract': False,
            },
            bases=('ansible_api.group',),
        ),
    ]
