# Generated by Django 2.1.2 on 2019-02-18 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0009_nodechangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodechangelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
