# Generated by Django 2.1.2 on 2018-12-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0010_auto_20181207_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(default='idle', max_length=128),
        ),
    ]
