# Generated by Django 2.1.2 on 2019-03-19 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0010_auto_20190319_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 19, 10, 5, 23, 73407, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
