# Generated by Django 2.1.2 on 2019-03-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0011_hostinfo_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'get_latest_by': 'date_created'},
        ),
    ]
