# Generated by Django 2.1.2 on 2019-02-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0013_auto_20190220_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='memory',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='os_version',
            field=models.CharField(default='', max_length=128),
        ),
    ]
