# Generated by Django 2.1.2 on 2019-02-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0015_auto_20190220_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='cpu_core',
        ),
        migrations.RemoveField(
            model_name='node',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='node',
            name='os',
        ),
        migrations.RemoveField(
            model_name='node',
            name='os_version',
        ),
    ]
