# Generated by Django 2.1.2 on 2019-02-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0018_auto_20190220_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='openshift_api.Host'),
        ),
    ]
