# Generated by Django 2.1.2 on 2019-02-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0019_auto_20190220_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodechangelog',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodechangelog',
            name='original',
        ),
        migrations.RemoveField(
            model_name='nodechangelog',
            name='target',
        ),
        migrations.DeleteModel(
            name='NodeChangeLog',
        ),
    ]
