# Generated by Django 2.1.2 on 2019-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0020_auto_20190221_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployexecution',
            name='current_task',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deployexecution',
            name='progress',
            field=models.FloatField(blank=True, default=0.0, max_length=64, null=True),
        ),
    ]
