---
- name: Set provisioners project
  oc_project:
    state: present
    kubeconfig: "{{ mktemp.stdout }}/admin.kubeconfig"
    name: "{{ openshift_provisioners_project }}"

- name: Create temp directory for all our templates
  file: path={{mktemp.stdout}}/templates state=directory mode=0755
  changed_when: False
  check_mode: no

- include_tasks: generate_secrets.yaml

- include_tasks: generate_clusterrolebindings.yaml

- include_tasks: generate_serviceaccounts.yaml
