# Generated by Django 2.2.10 on 2020-03-17 06:56

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=65535)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('CLUSTER', 'CLUSTER')], default='SYSTEM', max_length=128)),
                ('level', models.CharField(choices=[('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('INFO', 'INFO')], default='INFO', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('LOCAL', 'LOCAL'), ('DINGTALK', 'DINGTALK'), ('WORKWEIXIN', 'WORKWEIXIN')], default='LOCAL', max_length=64)),
                ('vars', common.models.JsonDictTextField(default={})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vars', common.models.JsonDictTextField(default={})),
                ('type', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('CLUSTER', 'CLUSTER')], default='SYSTEM', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('receive', models.CharField(max_length=64, null=True)),
                ('user_id', models.CharField(max_length=64, null=True)),
                ('send_type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('LOCAL', 'LOCAL'), ('DINGTALK', 'DINGTALK'), ('WORKWEIXIN', 'WORKWEIXIN')], default='LOCAL', max_length=64)),
                ('receive_status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('WAITING', 'WAITING'), ('FAILED', 'FAILED')], default='WAITING', max_length=64)),
                ('read_status', models.CharField(choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_center.Message')),
            ],
        ),
    ]
