# Generated by Django 2.2.10 on 2020-03-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0002_add_user_notification_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreceiver',
            name='type',
        ),
        migrations.AlterField(
            model_name='userreceiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
