// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Fit2cloud Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/session/": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginCredential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Profile"
                        }
                    }
                }
            },
            "delete": {
                "description": "Logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {}
            }
        },
        "/auth/session/system": {
            "post": {
                "description": "Login by system user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login by system user",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginCredentialSystem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Profile"
                        }
                    }
                }
            }
        },
        "/backupAccounts/": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credentials"
                ],
                "summary": "Update a credential",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CredentialUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Credential"
                        }
                    }
                }
            }
        },
        "/backupAccounts/batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete credential list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credentials"
                ],
                "summary": "Delete credential list",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CredentialBatchOp"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/backupaccounts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show backupAccounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupAccounts"
                ],
                "summary": "Show all backupAccounts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            }
        },
        "/backupaccounts/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a backupAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupAccounts"
                ],
                "summary": "Create a backupAccount",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BackupAccountCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BackupAccount"
                        }
                    }
                }
            }
        },
        "/backupaccounts/batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete  backupAccount list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupAccounts"
                ],
                "summary": "Delete backupAccount list",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BackupAccountOp"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/backupaccounts/{name}/": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a backupAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupAccounts"
                ],
                "summary": "Update a backupAccount",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BackupAccountUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BackupAccount"
                        }
                    }
                }
            }
        },
        "/clusters/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show clusters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Show all clusters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            }
        },
        "/clusters/backup/files/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show backupFiles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupFiles"
                ],
                "summary": "Show all backupFiles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            }
        },
        "/clusters/backup/files/backup/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Backup CLuster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupFiles"
                ],
                "summary": "Backup CLuster",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClusterBackupFileCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/clusters/backup/files/restore/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Restore CLuster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupFiles"
                ],
                "summary": "Restore CLuster",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClusterBackupFileRestore"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/clusters/backup/files/{name}/": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete a BackupFile by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupFiles"
                ],
                "summary": "Delete a BackupFile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "backup file name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/clusters/backup/strategy/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a Backup Strategy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupStrategy"
                ],
                "summary": "Create a Backup Strategy",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClusterBackupStrategyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ClusterBackupStrategy"
                        }
                    }
                }
            }
        },
        "/clusters/backup/strategy/{clusterName}/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get Cluster Backup Strategy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backupStrategy"
                ],
                "summary": "Get Cluster Backup Strategy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ClusterBackupStrategy"
                        }
                    }
                }
            }
        },
        "/clusters/batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete cluster list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Delete cluster list",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "is force",
                        "name": "force",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClusterBatch"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/clusters/node/{clusterName}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get cluster nodes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Get cluster nodes",
                "responses": {}
            }
        },
        "/clusters/{name}/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Show a cluster",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Cluster"
                        }
                    }
                }
            }
        },
        "/credentials/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credentials"
                ],
                "summary": "Show all credentials",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credentials"
                ],
                "summary": "Create a credential",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CredentialCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Credential"
                        }
                    }
                }
            }
        },
        "/hosts/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show hosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Show all hosts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Create a host",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.HostCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Host"
                        }
                    }
                }
            }
        },
        "/hosts/batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete host list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "delete host list",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.HostOp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Host"
                        }
                    }
                }
            }
        },
        "/hosts/template/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "download template file for import hosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Download Host Template File",
                "responses": {}
            }
        },
        "/hosts/upload/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Upload File for import hosts",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Upload File for import",
                "responses": {}
            }
        },
        "/hosts/{name}/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "show a host by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Show a host",
                "parameters": [
                    {
                        "type": "string",
                        "description": "host name",
                        "name": "pageNum",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Host"
                        }
                    }
                }
            }
        },
        "/logs/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show system_logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system_logs"
                ],
                "summary": "Show all system_logs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            }
        },
        "/project/members": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show projectMembers by projectName",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projectMembers"
                ],
                "summary": "Show projectMembers by projectName",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "project name",
                        "name": "project",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            }
        },
        "/project/members/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a projectMember",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projectMembers"
                ],
                "summary": "Create a projectMember",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProjectMemberCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProjectMember"
                        }
                    }
                }
            }
        },
        "/project/resources": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show projectResources by projectName and resourceType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projectResources"
                ],
                "summary": "Show projectResources by projectName and resourceType",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "HOST",
                            "BACKUP_ACCOUNT"
                        ],
                        "type": "string",
                        "description": "resourceType enums",
                        "name": "resourceType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "project name",
                        "name": "project",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            }
        },
        "/projects/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show projects",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Show all projects",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create a project",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProjectCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Project"
                        }
                    }
                }
            }
        },
        "/projects/batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete  project list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Delete project list",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProjectOp"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/projects/{name}/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "show a project by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Show a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Project"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update a project",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProjectUpdate"
                        }
                    },
                    {
                        "type": "string",
                        "description": "project name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Project"
                        }
                    }
                }
            }
        },
        "/users/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Show all users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/page.Page"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Host"
                        }
                    }
                }
            }
        },
        "/users/batch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete user list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user list",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserOp"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/users/{name}/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "show a user by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Show a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BackupAccount": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "credential": {
                    "type": "string"
                },
                "credentialVars": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.BackupAccountCreate": {
            "type": "object",
            "required": [
                "bucket",
                "credentialVars",
                "name"
            ],
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "credentialVars": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "OSS",
                        "AZURE",
                        "SFTP"
                    ]
                }
            }
        },
        "dto.BackupAccountOp": {
            "type": "object",
            "required": [
                "items",
                "operation"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BackupAccount"
                    }
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "dto.BackupAccountUpdate": {
            "type": "object",
            "required": [
                "bucket",
                "credentialVars",
                "id",
                "name"
            ],
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "credentialVars": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "OSS",
                        "AZURE",
                        "SFTP"
                    ]
                }
            }
        },
        "dto.Cluster": {
            "type": "object",
            "properties": {
                "architectures": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dirty": {
                    "type": "boolean"
                },
                "logId": {
                    "type": "string"
                },
                "multiClusterRepositories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MultiClusterRepository"
                    }
                },
                "multiClusterRepository": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nodeSize": {
                    "type": "integer"
                },
                "preStatus": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "spec": {
                    "$ref": "#/definitions/model.ClusterSpec"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.ClusterBackupFileCreate": {
            "type": "object",
            "required": [
                "clusterBackupStrategyId",
                "clusterName",
                "folder",
                "name"
            ],
            "properties": {
                "clusterBackupStrategyId": {
                    "type": "string"
                },
                "clusterName": {
                    "type": "string"
                },
                "folder": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ClusterBackupFileRestore": {
            "type": "object",
            "required": [
                "clusterName",
                "name"
            ],
            "properties": {
                "backupAccount": {
                    "$ref": "#/definitions/model.BackupAccount"
                },
                "clusterName": {
                    "type": "string"
                },
                "file": {
                    "$ref": "#/definitions/model.ClusterBackupFile"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ClusterBackupStrategy": {
            "type": "object",
            "properties": {
                "backupAccountId": {
                    "type": "string"
                },
                "backupAccountName": {
                    "type": "string"
                },
                "clusterId": {
                    "type": "string"
                },
                "clusterName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "cron": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "saveNum": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.ClusterBackupStrategyRequest": {
            "type": "object",
            "required": [
                "backupAccountName",
                "clusterName"
            ],
            "properties": {
                "backupAccountName": {
                    "type": "string"
                },
                "clusterName": {
                    "type": "string"
                },
                "cron": {
                    "type": "integer",
                    "maximum": 300,
                    "minimum": 1
                },
                "id": {
                    "type": "string"
                },
                "saveNum": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ENABLE",
                        "DISABLE"
                    ]
                }
            }
        },
        "dto.ClusterBatch": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Cluster"
                    }
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "dto.Credential": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.CredentialBatchOp": {
            "type": "object",
            "required": [
                "items",
                "operation"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Credential"
                    }
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "dto.CredentialCreate": {
            "type": "object",
            "required": [
                "name",
                "type",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 30
                },
                "password": {
                    "type": "string"
                },
                "privateKey": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "password",
                        "privateKey"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.CredentialUpdate": {
            "type": "object",
            "required": [
                "id",
                "name",
                "type",
                "username"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 30
                },
                "password": {
                    "type": "string"
                },
                "privateKey": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "password",
                        "privateKey"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.Host": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string"
                },
                "clusterId": {
                    "type": "string"
                },
                "clusterName": {
                    "type": "string"
                },
                "cpuCore": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "credentialId": {
                    "type": "string"
                },
                "datastore": {
                    "type": "string"
                },
                "gpuInfo": {
                    "type": "string"
                },
                "gpuNum": {
                    "type": "integer"
                },
                "hasGpu": {
                    "type": "boolean"
                },
                "ip": {
                    "type": "string"
                },
                "memory": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "osVersion": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "projectName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "volumes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Volume"
                    }
                },
                "zoneId": {
                    "type": "string"
                },
                "zoneName": {
                    "type": "string"
                }
            }
        },
        "dto.HostCreate": {
            "type": "object",
            "required": [
                "credentialId",
                "ip",
                "name",
                "port"
            ],
            "properties": {
                "credentialId": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 30
                },
                "port": {
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 1
                }
            }
        },
        "dto.HostOp": {
            "type": "object",
            "required": [
                "items",
                "operation"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Host"
                    }
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "dto.LoginCredential": {
            "type": "object",
            "required": [
                "captchaId",
                "code",
                "language",
                "password",
                "username"
            ],
            "properties": {
                "authMethod": {
                    "type": "string"
                },
                "captchaId": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.LoginCredentialSystem": {
            "type": "object",
            "required": [
                "language",
                "password",
                "username"
            ],
            "properties": {
                "language": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.Profile": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.SessionUser"
                }
            }
        },
        "dto.Project": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectCreate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "maxLength": 30
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectMember": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectMemberCreate": {
            "type": "object",
            "required": [
                "projectName",
                "username"
            ],
            "properties": {
                "projectName": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "CLUSTER_MANAGER",
                        "PROJECT_MANAGER"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectOp": {
            "type": "object",
            "required": [
                "items",
                "operation"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Project"
                    }
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "dto.ProjectUpdate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.SessionUser": {
            "type": "object",
            "properties": {
                "isActive": {
                    "type": "boolean"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.UserCreate": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "isAdmin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.UserOp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.User"
                    }
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "dto.UserUpdate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6
                }
            }
        },
        "model.BackupAccount": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "credential": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ClusterBackupFile": {
            "type": "object",
            "properties": {
                "clusterBackupStrategyId": {
                    "type": "string"
                },
                "clusterId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "folder": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ClusterSpec": {
            "type": "object",
            "properties": {
                "architectures": {
                    "type": "string"
                },
                "calicoIpv4PoolIpip": {
                    "type": "string"
                },
                "ciliumNativeRoutingCidr": {
                    "type": "string"
                },
                "ciliumTunnelMode": {
                    "type": "string"
                },
                "ciliumVersion": {
                    "type": "string"
                },
                "containerdStorageDir": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dnsCacheVersion": {
                    "type": "string"
                },
                "dockerStorageDir": {
                    "type": "string"
                },
                "docker_subnet": {
                    "type": "string"
                },
                "enableDnsCache": {
                    "type": "string"
                },
                "flannelBackend": {
                    "type": "string"
                },
                "helmVersion": {
                    "type": "string"
                },
                "ingressControllerType": {
                    "type": "string"
                },
                "kubeApiServerPort": {
                    "type": "integer"
                },
                "kubeMaxPods": {
                    "type": "integer"
                },
                "kubeNetworkNodePrefix": {
                    "type": "integer"
                },
                "kubePodSubnet": {
                    "type": "string"
                },
                "kubeProxyMode": {
                    "type": "string"
                },
                "kubeRouter": {
                    "type": "string"
                },
                "kubeServiceSubnet": {
                    "type": "string"
                },
                "kubernetesAudit": {
                    "type": "string"
                },
                "lbKubeApiserverIp": {
                    "type": "string"
                },
                "networkInterface": {
                    "type": "string"
                },
                "networkType": {
                    "type": "string"
                },
                "nodeportAddress": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "runtimeType": {
                    "type": "string"
                },
                "supportGpu": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "upgradeVersion": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "workerAmount": {
                    "type": "integer"
                },
                "yumOperate": {
                    "type": "string"
                }
            }
        },
        "model.MultiClusterRepository": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "gitTimeout": {
                    "type": "integer"
                },
                "lastSyncHead": {
                    "type": "string"
                },
                "lastSyncTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "syncEnable": {
                    "type": "boolean"
                },
                "syncInterval": {
                    "type": "integer"
                },
                "syncStatus": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.Volume": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "hostId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "page.Page": {
            "type": "object",
            "properties": {
                "items": {},
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "KubeOperator Restful API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
