# Generated by Django 2.1.2 on 2019-07-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0003_auto_20190722_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('invalid', 'invalid'), ('valid', 'valid')], default='invalid', max_length=128),
        ),
    ]
