# Generated by Django 2.1.2 on 2019-09-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0013_remove_cluster_terraform_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployexecution',
            name='current_play',
        ),
        migrations.RemoveField(
            model_name='deployexecution',
            name='progress',
        ),
    ]
