# Generated by Django 2.1.2 on 2019-09-18 10:39

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0015_deployexecution_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='backup_storage',
            fields=[
                ('id', models.UUIDField(max_length=255,default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('credentials', common.models.JsonDictTextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('S3', 'S3'), ('OSS', 'OSS')], max_length=64)),
                ('status', models.CharField(choices=[('VALID1233', 'valid'), ('INVALID', 'invalid')], default='VALID1233', max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
