# Generated by Django 2.1.2 on 2019-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0023_backupstrategy_clusterbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('CREATING', 'creating'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=128),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('INSTALLING', 'installing'), ('DELETING', 'deleting'), ('READY', 'ready'), ('ERROR', 'error'), ('WARNING', 'warning'), ('UPGRADING', 'upgrading'), ('SCALING', 'scaling')], default='READY', max_length=128),
        ),
    ]
