# Generated by Django 2.1.11 on 2019-11-04 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kubeops_api', '0039_dns'),
    ]

    def forwards_func(apps, schema_editor):
        DNS = apps.get_model("kubeops_api", "DNS")
        db_alias = schema_editor.connection.alias
        DNS.objects.using(db_alias).create(dns1="114.114.114.114", dns2="8.8.8.8")

    def reverse_func(apps, schema_editor):
        DNS = apps.get_model("kubeops_api", "DNS")
        db_alias = schema_editor.connection.alias
        for dns in DNS.objects.using(db_alias).all():
            dns.delete()

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
