# Generated by Django 2.1.2 on 2019-07-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0003_auto_20190730_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Comment'),
        ),
    ]
