# Generated by Django 2.1.2 on 2019-08-20 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0010_cluster_deploy_type'),
        ('cloud_provider', '0014_auto_20190814_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('domain', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=128)),
                ('cpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('short_name', models.CharField(max_length=128)),
                ('host_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubeops_api.Host')),
            ],
        ),
    ]
