# Generated by Django 2.1.2 on 2019-09-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0018_remove_terraformhost_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='deploy_template',
            field=models.CharField(choices=[('SINGLE', 'single'), ('MULTIPLE', 'multiple')], default='SINGLE', max_length=128),
        ),
        migrations.AddField(
            model_name='plan',
            name='zones',
            field=models.ManyToManyField(null=True, related_name='zones', to='cloud_provider.Zone'),
        ),
        migrations.AddField(
            model_name='terraformhost',
            name='zone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
