# Generated by Django 2.1.2 on 2019-03-04 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=128)),
                ('helper', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
