# Generated by Django 2.1.2 on 2019-03-12 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0003_auto_20190304_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployexecution',
            name='operation',
            field=models.CharField(blank=True, choices=[('install', 'install'), ('upgrade', 'upgrade'), ('uninstall', 'uninstall'), ('update', 'update')], default='install', max_length=128),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid name consisting of Unicode letters, numbers, underscores, or hyphens, or dot', regex='^[a-zA-Z0-9_\\-\\.]+$')]),
        ),
    ]
