# Generated by Django 2.1.2 on 2019-03-19 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0004_auto_20190312_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('size', models.FloatField(max_length=16)),
                ('blank', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_volume', to='openshift_api.Host')),
            ],
        ),
    ]
