# Generated by Django 2.1.2 on 2019-03-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0006_auto_20190319_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_info',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='host',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='host',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='openshift_api.Host'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='volumes',
            field=models.ManyToManyField(to='openshift_api.Volume'),
        ),
    ]
