# Generated by Django 2.1.2 on 2019-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0014_auto_20190408_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
