# Generated by Django 2.1.2 on 2019-04-08 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('openshift_api', '0015_auto_20190408_1321'),
    ]

    def forwards_func(apps, schema_editor):
        pass

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
