# Generated by Django 2.1.2 on 2019-05-27 04:04

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0002_auto_20190305_0555'),
        ('openshift_api', '0017_auto_20190412_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('meta', common.models.JsonDictTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Project')),
                ('vars', common.models.JsonDictTextField(default={})),
                ('status', models.CharField(choices=[('RUNNING', 'running'), ('UNKNOWN', 'unknown'), ('ERROR', 'error'), ('CHECKING', 'checking')], default='UNKNOWN', max_length=128)),
            ],
            bases=('ansible_api.project',),
        ),
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('host_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ansible_api.Host')),
                ('status', models.CharField(choices=[('RUNNING', 'running'), ('UNKNOWN', 'unknown'), ('ERROR', 'error')], default='UNKNOWN', max_length=128)),
                ('message', models.TextField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ansible_api.host',),
        ),
        migrations.CreateModel(
            name='StorageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('meta', common.models.JsonDictTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ('size',)},
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='current_task_id',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='is_super',
        ),
        migrations.RemoveField(
            model_name='deployexecution',
            name='current_task',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='blank',
        ),
        migrations.AddField(
            model_name='deployexecution',
            name='current_play',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deployexecution',
            name='extra_vars',
            field=common.models.JsonDictTextField(default={}),
        ),
        migrations.AlterField(
            model_name='deployexecution',
            name='operation',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='deployexecution',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='nodes',
            field=models.ManyToManyField(to='openshift_api.StorageNode'),
        ),
        migrations.AddField(
            model_name='storage',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openshift_api.StorageTemplate'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='persistent_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openshift_api.Storage'),
        ),
    ]
