# Generated by Django 2.1.2 on 2019-05-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0019_auto_20190527_0418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth',
            new_name='AuthTemplate',
        ),
    ]
