# Generated by Django 2.1.2 on 2019-05-27 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0020_auto_20190527_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='auth_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openshift_api.AuthTemplate'),
        ),
    ]
