# Generated by Django 2.1.2 on 2019-05-27 07:25

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0021_cluster_auth_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='vars',
            field=common.models.JsonTextField(blank=True, default={}, null=True, verbose_name='Meta'),
        ),
    ]
