# Generated by Django 2.1.2 on 2019-05-27 07:32

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0022_auto_20190527_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='vars',
            field=common.models.JsonDictTextField(blank=True, default={}, null=True, verbose_name='Vars'),
        ),
    ]
