# Generated by Django 2.1.2 on 2019-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0024_auto_20190528_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
