# Generated by Django 2.1.2 on 2019-06-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0026_remove_package_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='logo_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
