# Generated by Django 2.1.2 on 2019-06-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0028_remove_package_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='logo',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
